### PR TITLE
Dependabot/composer/doctrine/coding standard tw 10.0.0

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by malukenho** [comment]
The code looks good, but this is a BC break; it should not go to the `master` branch.

**Comment by icanhazstring** [comment]
Well it depends. Removing a supported php version is technically no breaking change. But that depends on how one defines it :)

**Comment by simPod** [comment]
@malukenho I agree with @malukenho but just tell me what branch to target eventually.

**Comment by malukenho** [comment]
@simPod I've pointed it to branch `2.0.x`. I can rebase and solve the conflicts if that is fine for you.

**Comment by simPod** [comment]
It is no logner relevant. Someone changed CS to laminas

**Pull request closed without merging**
