### PR TITLE
Update composer.lock after updating versions on the main file

### PR DESCRIPTION
**Pull request by renan**
In order to keep both files in sync.

### CODE REVIEW

**Comment by malukenho** [comment]
I think `composer` already updates the `locker` file after an update.
I'm missing the scenario here.

**Comment by renan** [comment]
The only time the `composer.lock` is updated is before this package' script is run. When the script is run it only update the `composer.json` file with the bumped version. Hence the `content-hash` in the `composer.lock` file no longer matches the `composer.json` file content.

**Comment by renan** [comment]
On a project of mine:

I want to update the packages to its latest versions
```
Loading composer repositories with package information
Updating dependencies (including require-dev)

Package operations: 0 installs, 3 updates, 0 removals
  - Updating alcaeus/mongo-php-adapter (1.1.10 => 1.1.11): Loading from cache
  - Updating doctrine/dbal (v2.10.0 => v2.10.1): Loading from cache
  - Updating ocramius/proxy-manager (2.2.3 => 2.5.1): Loading from cache

Writing lock file
Generating autoload files
malukenho/mcbumpface is updating alcaeus/mongo-php-adapter package from version (^1.1.10) to (^1.1.11)
malukenho/mcbumpface is updating doctrine/dbal package from version (^v2.10.0) to (^v2.10.1)
```

The git diff says:
```
diff --git a/composer.json b/composer.json
index df50e7ae..c582fc58 100755
--- a/composer.json
+++ b/composer.json
@@ -35,10 +35,10 @@
         "ext-mongo": "*",
         "ext-mongodb": "*",
         "ext-pdo": "*",
-        "alcaeus/mongo-php-adapter": "^1.1.10",
+        "alcaeus/mongo-php-adapter": "^1.1.11",
         "braintree/braintree_php": "^3.40.0",
         "components/jquery": "^2.2.4",
-        "doctrine/dbal": "^v2.10.0",
+        "doctrine/dbal": "^v2.10.1",
         "doctrine/doctrine-bundle": "^1.12.6",
         "doctrine/doctrine-migrations-bundle": "^v1.3.2",
         "doctrine/migrations": "^v1.8.1",
diff --git a/composer.lock b/composer.lock
index 96cd4e4e..168ed920 100644
--- a/composer.lock
+++ b/composer.lock
@@ -8,16 +8,16 @@
     "packages": [
         {
             "name": "alcaeus/mongo-php-adapter",
-            "version": "1.1.10",
+            "version": "1.1.11",
             "source": {
                 "type": "git",
                 "url": "https://github.com/alcaeus/mongo-php-adapter.git",
-                "reference": "d949a7b2048af3e32518cc0fde43321524d657d2"
+                "reference": "43b6add94c8b4cb9890d662cba4c0defde733dcf"
             },
             "dist": {
                 "type": "zip",
-                "url": "https://api.github.com/repos/alcaeus/mongo-php-adapter/zipball/d949a7b2048af3e32518cc0fde43321524d657d2",
-                "reference": "d949a7b2048af3e32518cc0fde43321524d657d2",
+                "url": "https://api.github.com/repos/alcaeus/mongo-php-adapter/zipball/43b6add94c8b4cb9890d662cba4c0defde733dcf",
+                "reference": "43b6add94c8b4cb9890d662cba4c0defde733dcf",
                 "shasum": ""
             },
             "require": {
@@ -70,7 +70,7 @@
                 "database",
                 "mongodb"
             ],
-            "time": "2019-11-06T19:47:30+00:00"
+            "time": "2019-11-11T20:47:32+00:00"
         },
         {
             "name": "braintree/braintree_php",
@@ -599,16 +599,16 @@
         },
         {
             "name": "doctrine/dbal",
-            "version": "v2.10.0",
+            "version": "v2.10.1",
             "source": {
                 "type": "git",
                 "url": "https://github.com/doctrine/dbal.git",
-                "reference": "0c9a646775ef549eb0a213a4f9bd4381d9b4d934"
+                "reference": "c2b8e6e82732a64ecde1cddf9e1e06cb8556e3d8"
             },
             "dist": {
                 "type": "zip",
-                "url": "https://api.github.com/repos/doctrine/dbal/zipball/0c9a646775ef549eb0a213a4f9bd4381d9b4d934",
-                "reference": "0c9a646775ef549eb0a213a4f9bd4381d9b4d934",
+                "url": "https://api.github.com/repos/doctrine/dbal/zipball/c2b8e6e82732a64ecde1cddf9e1e06cb8556e3d8",
+                "reference": "c2b8e6e82732a64ecde1cddf9e1e06cb8556e3d8",
                 "shasum": ""
             },
             "require": {
@@ -687,7 +687,7 @@
                 "sqlserver",
                 "sqlsrv"
             ],
-            "time": "2019-11-03T16:50:43+00:00"
+            "time": "2020-01-04T12:56:21+00:00"
         },
         {
             "name": "doctrine/doctrine-bundle",
@@ -2402,34 +2402,39 @@
         },
         {
             "name": "ocramius/proxy-manager",
-            "version": "2.2.3",
+            "version": "2.5.1",
             "source": {
                 "type": "git",
                 "url": "https://github.com/Ocramius/ProxyManager.git",
-                "reference": "4d154742e31c35137d5374c998e8f86b54db2e2f"
+                "reference": "b7bac968eef945322d1e28d7e833b6a549a6da27"
             },
             "dist": {
                 "type": "zip",
-                "url": "https://api.github.com/repos/Ocramius/ProxyManager/zipball/4d154742e31c35137d5374c998e8f86b54db2e2f",
-                "reference": "4d154742e31c35137d5374c998e8f86b54db2e2f",
+                "url": "https://api.github.com/repos/Ocramius/ProxyManager/zipball/b7bac968eef945322d1e28d7e833b6a549a6da27",
+                "reference": "b7bac968eef945322d1e28d7e833b6a549a6da27",
                 "shasum": ""
             },
             "require": {
-                "ocramius/package-versions": "^1.1.3",
-                "php": "^7.2.0",
-                "zendframework/zend-code": "^3.3.0"
+                "ocramius/package-versions": "^1.5.1",
+                "php": "^7.4.0",
+                "zendframework/zend-code": "^3.3.1"
+            },
+            "conflict": {
+                "doctrine/annotations": "<1.6.1",
+                "zendframework/zend-stdlib": "<3.2.1"
             },
             "require-dev": {
-                "couscous/couscous": "^1.6.1",
+                "couscous/couscous": "^1.7.2",
+                "doctrine/coding-standard": "^6.0.0",
                 "ext-phar": "*",
-                "humbug/humbug": "1.0.0-RC.0@RC",
-                "nikic/php-parser": "^3.1.1",
-                "padraic/phpunit-accelerator": "dev-master@DEV",
-                "phpbench/phpbench": "^0.12.2",
-                "phpstan/phpstan": "dev-master#856eb10a81c1d27c701a83f167dc870fd8f4236a as 0.9.999",
-                "phpstan/phpstan-phpunit": "dev-master#5629c0a1f4a9c417cb1077cf6693ad9753895761",
-                "phpunit/phpunit": "^6.4.3",
-                "squizlabs/php_codesniffer": "^2.9.1"
+                "infection/infection": "^0.13.4",
+                "nikic/php-parser": "^4.2.2",
+                "phpbench/phpbench": "^0.16.9",
+                "phpunit/phpunit": "^8.3.3",
+                "slevomat/coding-standard": "^5.0.4",
+                "squizlabs/php_codesniffer": "^3.4.2",
+                "symfony/console": "^4.3.3",
+                "vimeo/psalm": "3.4.11"
             },
             "suggest": {
                 "ocramius/generated-hydrator": "To have very fast object to array to object conversion for ghost objects",
@@ -2444,8 +2449,8 @@
                 }
             },
             "autoload": {
-                "psr-0": {
-                    "ProxyManager\\": "src"
+                "psr-4": {
+                    "ProxyManager\\": "src/ProxyManager"
                 }
             },
             "notification-url": "https://packagist.org/downloads/",
@@ -2468,7 +2473,7 @@
                 "proxy pattern",
                 "service proxies"
             ],
-            "time": "2019-08-10T08:37:15+00:00"
+            "time": "2019-12-17T09:22:43+00:00"
         },
         {
             "name": "paragonie/random_compat",
```

What happened here:
1. Composer downloaded the latest package versions
2. Composer updated `composer.lock`
3. Composer run `BumpInto::versions()` script
4. `BumpInto::versions()` updated `composer.json` file

Now,  if I run `composer install`, for example, it will complain the lock file is not up-to-date anymore:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Nothing to install or update
```

Which can be done by running `composer update` again, this time since there is no new packages only the `composer.lock` file will get updated with the correct `content-hash`:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
```

And now the diff with only `content-hash` changes:
```
diff --git a/composer.lock b/composer.lock
index 168ed920..c2331c41 100644
--- a/composer.lock
+++ b/composer.lock
@@ -4,7 +4,7 @@
         "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies",
         "This file is @generated automatically"
     ],
-    "content-hash": "37108942df27a7cb99cbd51a57bd6376",
+    "content-hash": "4b1483c0d876d6706cfc9bd61f709836",
     "packages": [
         {
             "name": "alcaeus/mongo-php-adapter",
```

I hope this is more clear now. This PR aims to update the `composer.lock` file so that everything is in sync.

**Comment by malukenho** [comment]
I'm not sure about changing the `lock` file directly.
Maybe we can trigger a `composer -u --lock` after the packages updates.

**Review by malukenho — APPROVED** [review]

**Comment by malukenho** [comment]
I'll fix it the tests a next MR.

Thank you @renan 🎊

**Pull request merged**
